### ISSUE TITLE
Author e-mails render strangely in `pkgdown`

### ISSUE THREAD

**Issue by jdhoffa** [maurolepore/reuse#7]
On the `pkgdown` site, the author information for @julie-vienne and @lindadelacombaz is rendering strangely. In particular, their e-mails are showing between their first and last names. 

<img width="238" alt="Screenshot 2022-04-05 at 11 22 14" src="https://user-images.githubusercontent.com/8741309/161722681-06c14e9f-a7f0-4e9b-b27e-05446b6fb6da.png">

**Comment by julie-vienne** [comment]
Between Mauro's name and his email address, there are two commas. Linda and I only used one. Do you know if this might be the cause? 

```
   c(person("Mauro", "Lepore**", ,** "maurolepore@gmail.com", role = c("aut", "ctr", "cre"),
           comment = c(ORCID = "0000-0002-1986-7988")),
      person("Julie","Vienne"**,**"j.vienne@hotmail.com", role = "aut",
           comment = c(ORCID = "0000-0002-2848-6095")),
```

**Comment by jdhoffa** [comment]
Nice catch, that is exactly it. Looking at the helpfile for `utils::person()`, I see that the function trace is
``` r
person(given = NULL, family = NULL, middle = NULL,
       email = NULL, role = NULL, comment = NULL,
       first = NULL, last = NULL) 
```
so it seems you guys are setting your e-mail as your middle name :-) 

@julie-vienne would you like to open a PR fixing this?
